name: Update Web App and Blob Storage

on:
  push:
    branches:
      - main

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.0"

      - name: Move to App and Install dependencies
        run: cd App/cantaso/ && npm install

      - name: Build React app
        run: cd App/cantaso/ && npm run build

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "cantasowebapp"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Publica el perfil desde los secretos de GitHub
          package: "./App/cantaso/build" # Ajusta según el directorio donde está tu build
